### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zzinzziny** [Atom-101/Danbooru-Dataset-Maker#1]
Thank you for your cool open source!

In generate_file_list.py, I encountered error messages.
how can I solve?

raceback (most recent call last):
  File "/Users/Innovator/Danbooru-Dataset-Maker/generate_file_list.py", line 102, in <module>
    handler(sys.argv[1]+"config.json")
IndexError: list index out of range

**Comment by Atom-101** [comment]
You need to provide the path to the config file when running the script. To use the provided config use this:

> python generate_file_list.py ./
